INSERT INTO fabricante(id, nombre) VALUES(1, 'Asus');
INSERT INTO fabricante(id, nombre) VALUES(2, 'Lenovo');
INSERT INTO fabricante(id, nombre) VALUES(3, 'Hewlett-Packard');
INSERT INTO fabricante(id, nombre) VALUES(4, 'Samsung');
INSERT INTO fabricante(id, nombre) VALUES(5, 'Seagate');
INSERT INTO fabricante(id, nombre) VALUES(6, 'Crucial');
INSERT INTO fabricante(id, nombre) VALUES(7, 'Gigabyte');
INSERT INTO fabricante(id, nombre) VALUES(8, 'Huawei');
INSERT INTO fabricante(id, nombre) VALUES(9, 'Xiaomi');

INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(2, 'Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(3, 'Intel i7 8700K', 489, 1);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(4, 'Geforce GTX 1050Ti', 105, 7);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(5, 'Geforce GTX 1080 Xtreme', 500, 7);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(6, 'Monitor 24 LED Full HD', 148, 3);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(7, 'Monitor 27 LED Full HD', 180, 3);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(8, 'Portátil Yoga 520', 600, 2);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(9, 'Portátil Ideapad 320', 444, 2);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(10, 'Impresora HP Deskjet 3720', 59, 3);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(11, 'Impresora HP Laserjet Pro M26nw', 180, 3);
